# -*- coding: utf-8 -*-
"""
/***************************************************************************
 complemento_prueba
                                 A QGIS plugin
 Complemento de ejemplo para explicar cómo se crea un complemento.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-16
        copyright            : (C) 2021 by Sergio Perea de la Casa
        email                : spc00033@red.ujaen.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load complemento_prueba class from file complemento_prueba.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .complemento_prueba import complemento_prueba
    return complemento_prueba(iface)
